#!/bin/bash
# set -x
# Raspberry Pi Internet Radio
# $Id: radio-config,v 1.3 2002/02/12 12:07:57 bob Exp $
#
# Author : Bob Rathbone
# Site   : http://www.bobrathbone.com
#
# Top level installation  program which calls /usr/share/radio/configure_radio.sh
#
# License: GNU V3, See https://www.gnu.org/copyleft/gpl.html
#
# Disclaimer: Software is provided as is and absolutly no warranties are implied or given.
#        The authors shall not be liable for any loss or damage however caused.

declare -r CHAR_ESC=$'\e'
DIR=/usr/share/radio
run=1
while [ $run == 1 ]
do
    ${DIR}/configure_radio.sh
    echo
    echo -n "Enter to continue or ESC to exit: " 
    read -s -n 1 ans
    if [[ $ans == "${CHAR_ESC}" ]] || [[ $ans == "q" ]]; then
        echo
        run=0
    fi
done

exit 0
