#!/bin/bash
# set -x
# Raspberry Pi Internet Radio
# $Id: radio-config,v 1.8 2002/02/24 16:31:38 bob Exp $
#
# Author : Bob Rathbone
# Site   : http://www.bobrathbone.com
#
# Top level installation  program which calls /usr/share/radio/configure_radio.sh
#
# License: GNU V3, See https://www.gnu.org/copyleft/gpl.html
#
# Disclaimer: Software is provided as is and absolutly no warranties are implied or given.
#        The authors shall not be liable for any loss or damage however caused.

FLAGS=$1

declare -r CHAR_ESC=$'\e'
DIR=/usr/share/radio
SCRIPTS=${DIR}/scripts

run=1
while [ $run == 1 ]
do
    ${SCRIPTS}/configure_radio.sh ${FLAGS}
    echo
    echo -n 'Enter to continue or ESC to exit: '
    read -s -n 1 ans
    if [[ $ans == "${CHAR_ESC}" ]] || [[ $ans == "q" ]]; then
        echo
        run=0
    fi
    printf '\e[A\e[K'
done

exit 0
