#!/bin/sh
#
# Raspberry Pi Internet Radio - Update radio stations
# $Id: radiod,v 1.1 2021/09/18 05:26:08 bob Exp $
#
# Author : Bob Rathbone
# Site   : http://www.bobrathbone.com
#
# This program is called from crontab to update /var/lib/radio/stationlist
# from the playlists found in /var/lib/mpd/playlists directory if 
# update_playlists=yes found in /etc/radiod.conf
# By default it stored in cron.daily
#
# License: GNU V3, See https://www.gnu.org/copyleft/gpl.html
#
# Disclaimer: Software is provided as is and absolutly no warranties are implied or given.
#            The authors shall not be liable for any loss or damage however caused

PATH=/sbin:/usr/sbin/:/usr/local/sbin:/bin:/usr/local/bin:/usr/bin

DIR=/usr/share/radio
LOGDIR=${DIR}/logs
LOG=${LOGDIR}/update_stationlist.log
CONFIG=/etc/radiod.conf

mkdir -p ${LOGDIR}
chown pi:pi ${LOGDIR}
grep "update_playlists=yes" ${CONFIG} 2>&1 >${LOG}
if [ $? -eq 0 ]; then
    sudo ${DIR}/update_stationlist.py --update 2>&1 >${LOG}
    sudo ${DIR}/create_stations.py --no_delete --force 2>&1 >${LOG}
fi
chown pi:pi ${LOG}
# End of script
