[[protocols]]
name = "myremote"
protocol = "nec"
variant = "nec"
[protocols.scancodes]
0xbf02 = "KEY_VOLUMEUP"
0xbf00 = "KEY_VOLUMEDOWN"
0xbf01 = "KEY_MUTE"
0xbf05 = "KEY_CHANNELUP"
0xbf0d = "KEY_CHANNELDOWN"
0xbf09 = "KEY_MENU"
0xbf08 = "KEY_LEFT"
0xbf0a = "KEY_RIGHT"
0xbf0c = "KEY_NUMERIC_0"
0xbf10 = "KEY_NUMERIC_1"
0xbf11 = "KEY_NUMERIC_2"
0xbf12 = "KEY_NUMERIC_3"
0xbf14 = "KEY_NUMERIC_4"
0xbf15 = "KEY_NUMERIC_5"
0xbf16 = "KEY_NUMERIC_6"
0xbf18 = "KEY_NUMERIC_7"
0xbf19 = "KEY_NUMERIC_8"
0xbf1a = "KEY_NUMERIC_9"
0xbf0e = "KEY_EXIT"
