#!/bin/sh
#
# Raspberry Pi Internet Radio remote control daemon
# $Id: irradiod,v 1.2 2018/05/21 10:13:51 bob Exp $
#
# Author : Bob Rathbone
# Site   : http://www.bobrathbone.com
#
# This script controls the piface remote control daemon
#
# License: GNU V3, See https://www.gnu.org/copyleft/gpl.html
#
# Disclaimer: Software is provided as is and absolutly no warranties are implied or given.
#             The authors shall not be liable for any loss or damage however caused.
#
### BEGIN INIT INFO
# Provides:          irradiod
# Should-Start:      
# Should-Stop:       
# Required-Start:    $remote_fs $syslog   
# Required-Stop:     $remote_fs $syslog 
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Raspberry pi Internet radio remote control daemon
# Description:       Start the Remote control daemon Daemon service
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

if [ -d /usr/share/radio ]; then
	DIR=/usr/share/radio
else
	DIR=/home/pi/radio
fi

NAME=remote_control.py
DESC="LIRC CAD remote control daemon"
DAEMON=${DIR}/${NAME}
LIRC=/etc/lirc/lircd.conf
LIRCD=/usr/sbin/lircd

# Exit if the package is not installed
if [ ! -x "$LIRCD" ];  then
	echo "LIRC package not installed - exiting"
	exit 1
fi

# Exit if the package is not installed
if [ ! -f "$LIRC" ];  then
	echo "${LIRC} not found - exiting"
	exit 1
fi

case "$1" in
    start)
        ${DAEMON} start
        ;;
    stop)
        ${DAEMON} stop
        ;;
    status)
        ${DAEMON} status
	;;
    version)
        ${DAEMON} version
	;;
    restart)
        ${DAEMON} restart
        ;;
    flash)
        ${DAEMON} flash
        ;;
    force-reload)
        ${DAEMON} restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status|flash|version}"
        exit 2
        ;;
esac
