#!/bin/sh
#
# Raspberry Pi Internet Radio Init script
# Obsolete system V script but retained for some backward compatability.
# The new startup script is in /lib/systemd/system/radiod.service (Systemd script)

# $Id: radiod,v 1.3 2020/02/27 10:54:48 bob Exp $
#
# Author : Bob Rathbone
# Site   : http://www.bobrathbone.com
#
# This script controls the radiod service
#
# License: GNU V3, See https://www.gnu.org/copyleft/gpl.html
#
# Disclaimer: Software is provided as is and absolutly no warranties are implied or given.
# The authors shall not be liable for any loss or damage however caused.
#
### BEGIN INIT INFO
# Provides:          radiod
# Should-Start:      
# Should-Stop:       
# Required-Start:    $remote_fs $syslog   
# Required-Stop:     $remote_fs $syslog 
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Raspberry PI Radio Daemon
# Description:       Start the Radio Daemon (radiod) service
#                    for network access to the local audio queue.
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

if [ -d /usr/share/radio ]; then
   DIR=/usr/share/radio
else
   DIR=/home/pi/radio
fi

NAME=radiod.py
DESC="PI Radio Daemon"
DAEMON=${DIR}/${NAME}
PIDFILE=/var/run/radiod.pid

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

case "$1" in
    start)
        ${DAEMON} start
        ;;
    stop)
        ${DAEMON} stop
        ;;
    status)
        ${DAEMON} status
	;;
    version)
        ${DAEMON} version
	;;
    restart)
        ${DAEMON} restart
        ;;
    info)
	echo -n "${NAME} " 
        ${DAEMON} version
	if [ -f ${PIDFILE} ]; then
		echo ${NAME} Running PID $(cat ${PIDFILE})
	else
		echo ${NAME} Not running
	fi
	mpd -V | grep Daemon
	grep PRETTY_NAME /etc/os-release | sed -e s/PRETTY_NAME=// -e s/\"//g
	uname -a
	echo
        ;;
    force-reload)
        ${DAEMON} restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status|info|version}"
        exit 2
        ;;
esac
